### PR TITLE
send data as hash, not the query string

### PR DESCRIPTION
**Pull request by Shkrt**
This PR solves issue #20 that makes impossible to create a ticket with long enough body. Tested with body consisting of 1000000 characters.

### CODE REVIEW

**Comment by Fodoj** [comment]
Tests fail :-(

**Comment by Fodoj** [comment]
And please add new tests for this issue, so bug doesn't appear again

**Comment by Shkrt** [comment]
* Fixed failing spec - the issue was that the Webmock does not recognize url parameters,unless url is passed as regexp.

* Updated ruby version for Travis builds - this was the second cause of failing specs.

* I have no clue what exactly should we test when coming to issue #20. All the action happens on httparty side, and we can only stub the request to return some dummy data, but how this can be useful in our case? Don't you think it's pointless to test private methods, that use third-party gem's API, when the only problem is the parameter name? I'd be happy if you point me to the right direction.

**Comment by Fodoj** [comment]
Many many thanks

**Pull request merged**
